
replicaCount: 1

image:
  repository: vaccinatie_punt_inventaris-main-postgres
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secret:
  name: db-env-secret

service: 
  port: 5432
  targetPort: 5432
  name: "postgresservice"

volumeClaimName: postgres-pv-claim
persistentVolumeName: task-pv-volume
persistentVolumeStorage: 10Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

envDb:
  normal: 
    POSTGRES_URL: "jdbc:postgresql://postgresserver-service:5432/vaccinatiepunt_inventaris"
  secret:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: vaccinatiepunt_inventaris

nodeSelector: {}
