apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-chart.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-chart.name" . }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: {{ include "helm-chart.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
        env:
          {{- include "helpers.list-envBackend-variables" . | indent 10 }}
        resources:
          {{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Always