
replicaCount: 1

image:
  repository: vaccinatie_punt_inventaris-main-backend
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secret:
  name: backend-env-secret

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  name: "vaccinatie-punt-inventaris-backend-service"
  nodePort: 30808

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

envBackend:
  secret:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_URL: "jdbc:postgresql://postgresserver-service:5432/vaccinatiepunt_inventaris"

nodeSelector: {}
